
version: '3.8'

services:
  luxury_catalog-php_container:
    build:
      context: etc/infrastructure/php
      dockerfile: Dockerfile
    container_name: luxury_catalog-php_container
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 9001:9000

  luxury_catalog-nginx_container:
    image: nginx:latest
    container_name: luxury_catalog-nginx_container
    ports:
      - 8000:80
    volumes:
      - ./etc/infrastructure/nginx/conf.d:/etc/nginx/conf.d
      - ./apps/LuxuryCatalogAPI/public/:/app/apps/LuxuryCatalogAPI/public
    depends_on:
      - luxury_catalog-php_container

  luxury_catalog-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    container_name: elasticsearch
    ports: [ '9200:9200' ]
    environment:
      - "ELASTIC_PASSWORD=elastic"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
      - "TAKE_FILE_OWNERSHIP=1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - './var/elasticsearch:/usr/share/elasticsearch/data'
