parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $client: '@elasticsearch.client'

    LuxuryCatalogAPI\:
        resource: '../src/'

    Catalog\:
      resource: '../../../src/Catalog/'

    Shared\:
        resource: '../../../src/Shared/'

    shared.infrastructure.persistence.elasticsearch.elasticsearch_client_factory:
        class: Shared\Infrastructure\Symfony\Persistence\Elasticsearch\ElasticsearchClientFactory
        arguments:
            $host: '%env(ELASTICSEARCH_API_BASE_URL)%'

    elasticsearch.client:
        class: Elasticsearch\Client
        factory: '@shared.infrastructure.persistence.elasticsearch.elasticsearch_client_factory'

    Shared\Infrastructure\Symfony\Bus\Query\SymfonyQueryBus:
        arguments:
            $bus: '@query.bus'

    Shared\Infrastructure\Symfony\Controller\ApiExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onException }

    _instanceof:
        Shared\Domain\Bus\Command\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }
        Shared\Domain\Bus\Query\QueryHandler:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

    # Loads this specific normalizer to the serializer component
    property_normalizer:
        class: Symfony\Component\Serializer\Normalizer\PropertyNormalizer
        tags:
            - { name: serializer.normalizer }

framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
            query.bus:

